version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "This is the first acceptance test"
      - run: sleep 25
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "This is the second acceptance test"    
      - run: sleep 25
  three:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "This is the third acceptance test"    
      - run: sleep 25
  four:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "This is the fourth acceptance test"    
      - run: sleep 25
  deployment:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Alriught, fine. Let's deploy this!"    
      - run: sleep 25
workflows:
  version: 2
  build-one-and-two:
    jobs:
      - build
      - one:
          requires:
            - build
      - two: 
          requires:
            - build
      - three: 
          requires:
            - build
      - four: 
          requires:
            - build
      - confirm:
          type: approval
          requires: 
            - one
            - two
            - three
            - four
      - deployment:
          requires:
            - confirm
    morning-routine:
      triggers:
        - schedule:
            cron: "0 8 * * 1-5"
            filters: 
              branches: 
                only:
                  - master
                  - beta
      jobs:
        - build
        - one:
            requires:
              - build
        - two:
            requires:
              - one
        - three:
            requires:
              - one
