version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: my_workspace
          # Must be relative path from root
          paths:
            - echo-output 
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi"  
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: my_workspace

      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
  three:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "This is the third acceptance test"    
      - run: sleep 25
  four:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "This is the fourth acceptance test"    
      - run: sleep 25
  deployment:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Alriught, fine. Let's deploy this!"    
      - run: sleep 25
workflows:
  version: 2
  build-one-and-two:
    jobs:
      - build
      - one:
          requires:
            - build
      - two: 
          requires:
            - one
      - three: 
          requires:
            - two
      - four: 
          requires:
            - two
      - confirm:
          type: approval
          requires: 
            - one
            - two
            - three
            - four
      - deployment:
          requires:
            - confirm
  morning-routine:
    triggers:
      - schedule:
          cron: "0 8 * * 1-5"
          filters: 
            branches: 
              only:
                - master
                - beta
    jobs:
      - build
      - one:
          requires:
            - build
      - two:
          requires:
            - one
      - three:
          requires:
            - one
